/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductType = IDL.Variant({
  'book' : IDL.Null,
  'apparel' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'inventory' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'productType' : ProductType,
  'qrCodeImage' : IDL.Opt(IDL.Text),
  'image' : IDL.Opt(ExternalBlob),
  'price' : IDL.Nat,
});
export const PublicationStatus = IDL.Variant({
  'outOfStock' : IDL.Null,
  'comingSoon' : IDL.Null,
  'forSale' : IDL.Null,
});
export const PublicationFormat = IDL.Variant({
  'hardcover' : IDL.Null,
  'paperback' : IDL.Null,
  'kindle' : IDL.Null,
});
export const Publication = IDL.Record({
  'id' : IDL.Nat,
  'status' : PublicationStatus,
  'title' : IDL.Text,
  'amazonLink' : IDL.Opt(IDL.Text),
  'purchaseLink' : IDL.Opt(IDL.Text),
  'availableQuantity' : IDL.Nat,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'coverImage' : IDL.Opt(ExternalBlob),
  'summary' : IDL.Text,
  'price' : IDL.Nat,
  'format' : PublicationFormat,
});
export const Video = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
  'category' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SessionType = IDL.Variant({
  'mentoring' : IDL.Null,
  'consultation' : IDL.Null,
});
export const Time = IDL.Int;
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ApparelItem = IDL.Record({
  'id' : IDL.Nat,
  'purchaseLink' : IDL.Text,
  'inventory' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'productType' : ProductType,
  'qrCodeImage' : IDL.Opt(IDL.Text),
  'image' : IDL.Opt(ExternalBlob),
  'price' : IDL.Nat,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'sessionType' : SessionType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'appointmentTime' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
  'hasMembership' : IDL.Bool,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const Credentials = IDL.Record({
  'mastersDiplomaImage' : IDL.Text,
  'phdDiplomaImage' : IDL.Text,
  'portraitImage' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const TrainingDocument = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'documentUrl' : IDL.Text,
  'shortDescription' : IDL.Text,
});
export const TrainingVideo = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'shortDescription' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateMembership' : IDL.Func([IDL.Principal], [], []),
  'addProduct' : IDL.Func([Product], [IDL.Nat], []),
  'addPublication' : IDL.Func([Publication], [], []),
  'addVideo' : IDL.Func([Video], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, SessionType, Time],
      [IDL.Nat],
      [],
    ),
  'checkBookingAccess' : IDL.Func([], [IDL.Bool], ['query']),
  'checkStoreAccess' : IDL.Func([], [IDL.Bool], ['query']),
  'checkVideoAccess' : IDL.Func([], [IDL.Bool], ['query']),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat), IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deactivateMembership' : IDL.Func([IDL.Principal], [], []),
  'deletePublication' : IDL.Func([IDL.Nat], [], []),
  'getAllApparel' : IDL.Func([], [IDL.Vec(ApparelItem)], ['query']),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getBiographyContent' : IDL.Func(
      [],
      [
        IDL.Record({
          'headline' : IDL.Text,
          'education' : IDL.Text,
          'expertise' : IDL.Text,
          'philosophy' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'email' : IDL.Text,
          'phone' : IDL.Text,
          'location' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getCredentials' : IDL.Func([], [Credentials], ['query']),
  'getDistinguishedServiceProfiles' : IDL.Func(
      [],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getMembershipPlans' : IDL.Func([], [IDL.Vec(ShoppingItem)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getPublication' : IDL.Func([IDL.Nat], [Publication], ['query']),
  'getPublications' : IDL.Func([], [IDL.Vec(Publication)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTrainingDocument' : IDL.Func([IDL.Nat], [TrainingDocument], ['query']),
  'getTrainingDocuments' : IDL.Func([], [IDL.Vec(TrainingDocument)], ['query']),
  'getTrainingVideo' : IDL.Func([IDL.Nat], [TrainingVideo], ['query']),
  'getTrainingVideos' : IDL.Func([], [IDL.Vec(TrainingVideo)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserMember' : IDL.Func([], [IDL.Bool], ['query']),
  'purchaseMembership' : IDL.Func(
      [ShoppingItem, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePublication' : IDL.Func([IDL.Nat, Publication], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductType = IDL.Variant({ 'book' : IDL.Null, 'apparel' : IDL.Null });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'inventory' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'productType' : ProductType,
    'qrCodeImage' : IDL.Opt(IDL.Text),
    'image' : IDL.Opt(ExternalBlob),
    'price' : IDL.Nat,
  });
  const PublicationStatus = IDL.Variant({
    'outOfStock' : IDL.Null,
    'comingSoon' : IDL.Null,
    'forSale' : IDL.Null,
  });
  const PublicationFormat = IDL.Variant({
    'hardcover' : IDL.Null,
    'paperback' : IDL.Null,
    'kindle' : IDL.Null,
  });
  const Publication = IDL.Record({
    'id' : IDL.Nat,
    'status' : PublicationStatus,
    'title' : IDL.Text,
    'amazonLink' : IDL.Opt(IDL.Text),
    'purchaseLink' : IDL.Opt(IDL.Text),
    'availableQuantity' : IDL.Nat,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'coverImage' : IDL.Opt(ExternalBlob),
    'summary' : IDL.Text,
    'price' : IDL.Nat,
    'format' : PublicationFormat,
  });
  const Video = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
    'category' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SessionType = IDL.Variant({
    'mentoring' : IDL.Null,
    'consultation' : IDL.Null,
  });
  const Time = IDL.Int;
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ApparelItem = IDL.Record({
    'id' : IDL.Nat,
    'purchaseLink' : IDL.Text,
    'inventory' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'productType' : ProductType,
    'qrCodeImage' : IDL.Opt(IDL.Text),
    'image' : IDL.Opt(ExternalBlob),
    'price' : IDL.Nat,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'sessionType' : SessionType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'appointmentTime' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
    'hasMembership' : IDL.Bool,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const Credentials = IDL.Record({
    'mastersDiplomaImage' : IDL.Text,
    'phdDiplomaImage' : IDL.Text,
    'portraitImage' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const TrainingDocument = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'documentUrl' : IDL.Text,
    'shortDescription' : IDL.Text,
  });
  const TrainingVideo = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'shortDescription' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateMembership' : IDL.Func([IDL.Principal], [], []),
    'addProduct' : IDL.Func([Product], [IDL.Nat], []),
    'addPublication' : IDL.Func([Publication], [], []),
    'addVideo' : IDL.Func([Video], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, SessionType, Time],
        [IDL.Nat],
        [],
      ),
    'checkBookingAccess' : IDL.Func([], [IDL.Bool], ['query']),
    'checkStoreAccess' : IDL.Func([], [IDL.Bool], ['query']),
    'checkVideoAccess' : IDL.Func([], [IDL.Bool], ['query']),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat), IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deactivateMembership' : IDL.Func([IDL.Principal], [], []),
    'deletePublication' : IDL.Func([IDL.Nat], [], []),
    'getAllApparel' : IDL.Func([], [IDL.Vec(ApparelItem)], ['query']),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getBiographyContent' : IDL.Func(
        [],
        [
          IDL.Record({
            'headline' : IDL.Text,
            'education' : IDL.Text,
            'expertise' : IDL.Text,
            'philosophy' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'email' : IDL.Text,
            'phone' : IDL.Text,
            'location' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getCredentials' : IDL.Func([], [Credentials], ['query']),
    'getDistinguishedServiceProfiles' : IDL.Func(
        [],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getMembershipPlans' : IDL.Func([], [IDL.Vec(ShoppingItem)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getPublication' : IDL.Func([IDL.Nat], [Publication], ['query']),
    'getPublications' : IDL.Func([], [IDL.Vec(Publication)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTrainingDocument' : IDL.Func([IDL.Nat], [TrainingDocument], ['query']),
    'getTrainingDocuments' : IDL.Func(
        [],
        [IDL.Vec(TrainingDocument)],
        ['query'],
      ),
    'getTrainingVideo' : IDL.Func([IDL.Nat], [TrainingVideo], ['query']),
    'getTrainingVideos' : IDL.Func([], [IDL.Vec(TrainingVideo)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserMember' : IDL.Func([], [IDL.Bool], ['query']),
    'purchaseMembership' : IDL.Func(
        [ShoppingItem, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePublication' : IDL.Func([IDL.Nat, Publication], [], []),
  });
};

export const init = ({ IDL }) => { return []; };