/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Video {
    id: bigint;
    title: string;
    thumbnail?: ExternalBlob;
    description: string;
    category: string;
    videoUrl: string;
}
export interface Product {
    id: bigint;
    inventory: bigint;
    name: string;
    description: string;
    productType: ProductType;
    qrCodeImage?: string;
    image?: ExternalBlob;
    price: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface ContactSubmission {
    id: bigint;
    name: string;
    submittedAt: Time;
    email: string;
    message: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Credentials {
    mastersDiplomaImage: string;
    phdDiplomaImage: string;
    portraitImage: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ApparelItem {
    id: bigint;
    purchaseLink: string;
    inventory: bigint;
    name: string;
    description: string;
    productType: ProductType;
    qrCodeImage?: string;
    image?: ExternalBlob;
    price: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface TrainingVideo {
    id: bigint;
    title: string;
    shortDescription: string;
    videoUrl: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TrainingDocument {
    id: bigint;
    title: string;
    documentUrl: string;
    shortDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface Publication {
    id: bigint;
    status: PublicationStatus;
    title: string;
    amazonLink?: string;
    purchaseLink?: string;
    availableQuantity: bigint;
    description: string;
    author: string;
    coverImage?: ExternalBlob;
    summary: string;
    price: bigint;
    format: PublicationFormat;
}
export interface Appointment {
    id: bigint;
    sessionType: SessionType;
    name: string;
    email: string;
    appointmentTime: Time;
}
export interface UserProfile {
    name: string;
    email: string;
    phone?: string;
    hasMembership: boolean;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ProductType {
    book = "book",
    apparel = "apparel"
}
export enum PublicationFormat {
    hardcover = "hardcover",
    paperback = "paperback",
    kindle = "kindle"
}
export enum PublicationStatus {
    outOfStock = "outOfStock",
    comingSoon = "comingSoon",
    forSale = "forSale"
}
export enum SessionType {
    mentoring = "mentoring",
    consultation = "consultation"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    activateMembership(user: Principal): Promise<void>;
    addProduct(product: Product): Promise<bigint>;
    addPublication(_publication: Publication): Promise<void>;
    addVideo(video: Video): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookAppointment(name: string, email: string, sessionType: SessionType, appointmentTime: Time): Promise<bigint>;
    checkBookingAccess(): Promise<boolean>;
    checkStoreAccess(): Promise<boolean>;
    checkVideoAccess(): Promise<boolean>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createOrder(customerName: string, customerEmail: string, productIds: Array<bigint>, totalPrice: bigint): Promise<bigint>;
    deactivateMembership(user: Principal): Promise<void>;
    deletePublication(_id: bigint): Promise<void>;
    getAllApparel(): Promise<Array<ApparelItem>>;
    getAppointments(): Promise<Array<Appointment>>;
    getBiographyContent(): Promise<{
        headline: string;
        education: string;
        expertise: string;
        philosophy: string;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContactInfo(): Promise<{
        email: string;
        phone: string;
        location: string;
    }>;
    getContactSubmissions(): Promise<Array<ContactSubmission>>;
    getCredentials(): Promise<Credentials>;
    getDisplayName(): Promise<string>;
    getDistinguishedServiceProfiles(): Promise<Array<UserProfile>>;
    getMembershipPlans(): Promise<Array<ShoppingItem>>;
    getProducts(): Promise<Array<Product>>;
    getPublication(id: bigint): Promise<Publication>;
    getPublications(): Promise<Array<Publication>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTrainingDocument(id: bigint): Promise<TrainingDocument>;
    getTrainingDocuments(): Promise<Array<TrainingDocument>>;
    getTrainingVideo(id: bigint): Promise<TrainingVideo>;
    getTrainingVideos(): Promise<Array<TrainingVideo>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVideos(): Promise<Array<Video>>;
    hasDisplayName(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    isUserMember(): Promise<boolean>;
    purchaseMembership(plan: ShoppingItem, successUrl: string, cancelUrl: string): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setDisplayName(name: string): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitContactForm(name: string, email: string, message: string): Promise<bigint>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updatePublication(_id: bigint, _publication: Publication): Promise<void>;
}
import type { ApparelItem as _ApparelItem, Appointment as _Appointment, ExternalBlob as _ExternalBlob, Product as _Product, ProductType as _ProductType, Publication as _Publication, PublicationFormat as _PublicationFormat, PublicationStatus as _PublicationStatus, SessionType as _SessionType, StripeSessionStatus as _StripeSessionStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, Video as _Video, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async activateMembership(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateMembership(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateMembership(arg0);
            return result;
        }
    }
    async addProduct(arg0: Product): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(await to_candid_Product_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(await to_candid_Product_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPublication(arg0: Publication): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPublication(await to_candid_Publication_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPublication(await to_candid_Publication_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addVideo(arg0: Video): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addVideo(await to_candid_Video_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVideo(await to_candid_Video_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookAppointment(arg0: string, arg1: string, arg2: SessionType, arg3: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(arg0, arg1, to_candid_SessionType_n23(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(arg0, arg1, to_candid_SessionType_n23(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async checkBookingAccess(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkBookingAccess();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkBookingAccess();
            return result;
        }
    }
    async checkStoreAccess(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkStoreAccess();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkStoreAccess();
            return result;
        }
    }
    async checkVideoAccess(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkVideoAccess();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkVideoAccess();
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createOrder(arg0: string, arg1: string, arg2: Array<bigint>, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deactivateMembership(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateMembership(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateMembership(arg0);
            return result;
        }
    }
    async deletePublication(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePublication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePublication(arg0);
            return result;
        }
    }
    async getAllApparel(): Promise<Array<ApparelItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApparel();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApparel();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointments();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointments();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBiographyContent(): Promise<{
        headline: string;
        education: string;
        expertise: string;
        philosophy: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getBiographyContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBiographyContent();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactInfo(): Promise<{
        email: string;
        phone: string;
        location: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactInfo();
            return result;
        }
    }
    async getContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmissions();
            return result;
        }
    }
    async getCredentials(): Promise<Credentials> {
        if (this.processError) {
            try {
                const result = await this.actor.getCredentials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCredentials();
            return result;
        }
    }
    async getDisplayName(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getDisplayName();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDisplayName();
            return result;
        }
    }
    async getDistinguishedServiceProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDistinguishedServiceProfiles();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDistinguishedServiceProfiles();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembershipPlans(): Promise<Array<ShoppingItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembershipPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembershipPlans();
            return result;
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublication(arg0: bigint): Promise<Publication> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublication(arg0);
                return from_candid_Publication_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublication(arg0);
            return from_candid_Publication_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublications(): Promise<Array<Publication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublications();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublications();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrainingDocument(arg0: bigint): Promise<TrainingDocument> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainingDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainingDocument(arg0);
            return result;
        }
    }
    async getTrainingDocuments(): Promise<Array<TrainingDocument>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainingDocuments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainingDocuments();
            return result;
        }
    }
    async getTrainingVideo(arg0: bigint): Promise<TrainingVideo> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainingVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainingVideo(arg0);
            return result;
        }
    }
    async getTrainingVideos(): Promise<Array<TrainingVideo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainingVideos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainingVideos();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideos(): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideos();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideos();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasDisplayName(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasDisplayName();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasDisplayName();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async isUserMember(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserMember();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserMember();
            return result;
        }
    }
    async purchaseMembership(arg0: ShoppingItem, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseMembership(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseMembership(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n60(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n60(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setDisplayName(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDisplayName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDisplayName(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updatePublication(arg0: bigint, arg1: Publication): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePublication(arg0, await to_candid_Publication_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePublication(arg0, await to_candid_Publication_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_ApparelItem_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApparelItem): Promise<ApparelItem> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ProductType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductType): ProductType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_PublicationFormat_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicationFormat): PublicationFormat {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_PublicationStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicationStatus): PublicationStatus {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
async function from_candid_Publication_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Publication): Promise<Publication> {
    return await from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_SessionType_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionType): SessionType {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
async function from_candid_Video_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Video): Promise<Video> {
    return await from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    purchaseLink: string;
    inventory: bigint;
    name: string;
    description: string;
    productType: _ProductType;
    qrCodeImage: [] | [string];
    image: [] | [_ExternalBlob];
    price: bigint;
}): Promise<{
    id: bigint;
    purchaseLink: string;
    inventory: bigint;
    name: string;
    description: string;
    productType: ProductType;
    qrCodeImage?: string;
    image?: ExternalBlob;
    price: bigint;
}> {
    return {
        id: value.id,
        purchaseLink: value.purchaseLink,
        inventory: value.inventory,
        name: value.name,
        description: value.description,
        productType: from_candid_ProductType_n28(_uploadFile, _downloadFile, value.productType),
        qrCodeImage: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.qrCodeImage)),
        image: record_opt_to_undefined(await from_candid_opt_n31(_uploadFile, _downloadFile, value.image)),
        price: value.price
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    sessionType: _SessionType;
    name: string;
    email: string;
    appointmentTime: _Time;
}): {
    id: bigint;
    sessionType: SessionType;
    name: string;
    email: string;
    appointmentTime: Time;
} {
    return {
        id: value.id,
        sessionType: from_candid_SessionType_n36(_uploadFile, _downloadFile, value.sessionType),
        name: value.name,
        email: value.email,
        appointmentTime: value.appointmentTime
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    phone: [] | [string];
    hasMembership: boolean;
}): {
    name: string;
    email: string;
    phone?: string;
    hasMembership: boolean;
} {
    return {
        name: value.name,
        email: value.email,
        phone: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.phone)),
        hasMembership: value.hasMembership
    };
}
async function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    inventory: bigint;
    name: string;
    description: string;
    productType: _ProductType;
    qrCodeImage: [] | [string];
    image: [] | [_ExternalBlob];
    price: bigint;
}): Promise<{
    id: bigint;
    inventory: bigint;
    name: string;
    description: string;
    productType: ProductType;
    qrCodeImage?: string;
    image?: ExternalBlob;
    price: bigint;
}> {
    return {
        id: value.id,
        inventory: value.inventory,
        name: value.name,
        description: value.description,
        productType: from_candid_ProductType_n28(_uploadFile, _downloadFile, value.productType),
        qrCodeImage: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.qrCodeImage)),
        image: record_opt_to_undefined(await from_candid_opt_n31(_uploadFile, _downloadFile, value.image)),
        price: value.price
    };
}
async function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PublicationStatus;
    title: string;
    amazonLink: [] | [string];
    purchaseLink: [] | [string];
    availableQuantity: bigint;
    description: string;
    author: string;
    coverImage: [] | [_ExternalBlob];
    summary: string;
    price: bigint;
    format: _PublicationFormat;
}): Promise<{
    id: bigint;
    status: PublicationStatus;
    title: string;
    amazonLink?: string;
    purchaseLink?: string;
    availableQuantity: bigint;
    description: string;
    author: string;
    coverImage?: ExternalBlob;
    summary: string;
    price: bigint;
    format: PublicationFormat;
}> {
    return {
        id: value.id,
        status: from_candid_PublicationStatus_n49(_uploadFile, _downloadFile, value.status),
        title: value.title,
        amazonLink: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.amazonLink)),
        purchaseLink: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.purchaseLink)),
        availableQuantity: value.availableQuantity,
        description: value.description,
        author: value.author,
        coverImage: record_opt_to_undefined(await from_candid_opt_n31(_uploadFile, _downloadFile, value.coverImage)),
        summary: value.summary,
        price: value.price,
        format: from_candid_PublicationFormat_n51(_uploadFile, _downloadFile, value.format)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
async function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    thumbnail: [] | [_ExternalBlob];
    description: string;
    category: string;
    videoUrl: string;
}): Promise<{
    id: bigint;
    title: string;
    thumbnail?: ExternalBlob;
    description: string;
    category: string;
    videoUrl: string;
}> {
    return {
        id: value.id,
        title: value.title,
        thumbnail: record_opt_to_undefined(await from_candid_opt_n31(_uploadFile, _downloadFile, value.thumbnail)),
        description: value.description,
        category: value.category,
        videoUrl: value.videoUrl
    };
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    book: null;
} | {
    apparel: null;
}): ProductType {
    return "book" in value ? ProductType.book : "apparel" in value ? ProductType.apparel : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mentoring: null;
} | {
    consultation: null;
}): SessionType {
    return "mentoring" in value ? SessionType.mentoring : "consultation" in value ? SessionType.consultation : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    outOfStock: null;
} | {
    comingSoon: null;
} | {
    forSale: null;
}): PublicationStatus {
    return "outOfStock" in value ? PublicationStatus.outOfStock : "comingSoon" in value ? PublicationStatus.comingSoon : "forSale" in value ? PublicationStatus.forSale : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hardcover: null;
} | {
    paperback: null;
} | {
    kindle: null;
}): PublicationFormat {
    return "hardcover" in value ? PublicationFormat.hardcover : "paperback" in value ? PublicationFormat.paperback : "kindle" in value ? PublicationFormat.kindle : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n56(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApparelItem>): Promise<Array<ApparelItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ApparelItem_n26(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n39(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n45(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Publication>): Promise<Array<Publication>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Publication_n47(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Video>): Promise<Array<Video>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Video_n58(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ProductType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductType): _ProductType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_Product_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): Promise<_Product> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_PublicationFormat_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublicationFormat): _PublicationFormat {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_PublicationStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublicationStatus): _PublicationStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_Publication_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Publication): Promise<_Publication> {
    return await to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_SessionType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionType): _SessionType {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n61(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function to_candid_Video_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Video): Promise<_Video> {
    return await to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: PublicationStatus;
    title: string;
    amazonLink?: string;
    purchaseLink?: string;
    availableQuantity: bigint;
    description: string;
    author: string;
    coverImage?: ExternalBlob;
    summary: string;
    price: bigint;
    format: PublicationFormat;
}): Promise<{
    id: bigint;
    status: _PublicationStatus;
    title: string;
    amazonLink: [] | [string];
    purchaseLink: [] | [string];
    availableQuantity: bigint;
    description: string;
    author: string;
    coverImage: [] | [_ExternalBlob];
    summary: string;
    price: bigint;
    format: _PublicationFormat;
}> {
    return {
        id: value.id,
        status: to_candid_PublicationStatus_n15(_uploadFile, _downloadFile, value.status),
        title: value.title,
        amazonLink: value.amazonLink ? candid_some(value.amazonLink) : candid_none(),
        purchaseLink: value.purchaseLink ? candid_some(value.purchaseLink) : candid_none(),
        availableQuantity: value.availableQuantity,
        description: value.description,
        author: value.author,
        coverImage: value.coverImage ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.coverImage)) : candid_none(),
        summary: value.summary,
        price: value.price,
        format: to_candid_PublicationFormat_n17(_uploadFile, _downloadFile, value.format)
    };
}
async function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    thumbnail?: ExternalBlob;
    description: string;
    category: string;
    videoUrl: string;
}): Promise<{
    id: bigint;
    title: string;
    thumbnail: [] | [_ExternalBlob];
    description: string;
    category: string;
    videoUrl: string;
}> {
    return {
        id: value.id,
        title: value.title,
        thumbnail: value.thumbnail ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.thumbnail)) : candid_none(),
        description: value.description,
        category: value.category,
        videoUrl: value.videoUrl
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    phone?: string;
    hasMembership: boolean;
}): {
    name: string;
    email: string;
    phone: [] | [string];
    hasMembership: boolean;
} {
    return {
        name: value.name,
        email: value.email,
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        hasMembership: value.hasMembership
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    inventory: bigint;
    name: string;
    description: string;
    productType: ProductType;
    qrCodeImage?: string;
    image?: ExternalBlob;
    price: bigint;
}): Promise<{
    id: bigint;
    inventory: bigint;
    name: string;
    description: string;
    productType: _ProductType;
    qrCodeImage: [] | [string];
    image: [] | [_ExternalBlob];
    price: bigint;
}> {
    return {
        id: value.id,
        inventory: value.inventory,
        name: value.name,
        description: value.description,
        productType: to_candid_ProductType_n10(_uploadFile, _downloadFile, value.productType),
        qrCodeImage: value.qrCodeImage ? candid_some(value.qrCodeImage) : candid_none(),
        image: value.image ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.image)) : candid_none(),
        price: value.price
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductType): {
    book: null;
} | {
    apparel: null;
} {
    return value == ProductType.book ? {
        book: null
    } : value == ProductType.apparel ? {
        apparel: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublicationStatus): {
    outOfStock: null;
} | {
    comingSoon: null;
} | {
    forSale: null;
} {
    return value == PublicationStatus.outOfStock ? {
        outOfStock: null
    } : value == PublicationStatus.comingSoon ? {
        comingSoon: null
    } : value == PublicationStatus.forSale ? {
        forSale: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublicationFormat): {
    hardcover: null;
} | {
    paperback: null;
} | {
    kindle: null;
} {
    return value == PublicationFormat.hardcover ? {
        hardcover: null
    } : value == PublicationFormat.paperback ? {
        paperback: null
    } : value == PublicationFormat.kindle ? {
        kindle: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionType): {
    mentoring: null;
} | {
    consultation: null;
} {
    return value == SessionType.mentoring ? {
        mentoring: null
    } : value == SessionType.consultation ? {
        consultation: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
