/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApparelItem {
  'id' : bigint,
  'purchaseLink' : string,
  'inventory' : bigint,
  'name' : string,
  'description' : string,
  'productType' : ProductType,
  'qrCodeImage' : [] | [string],
  'image' : [] | [ExternalBlob],
  'price' : bigint,
}
export interface Appointment {
  'id' : bigint,
  'sessionType' : SessionType,
  'name' : string,
  'email' : string,
  'appointmentTime' : Time,
}
export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'submittedAt' : Time,
  'email' : string,
  'message' : string,
}
export interface Credentials {
  'mastersDiplomaImage' : string,
  'phdDiplomaImage' : string,
  'portraitImage' : string,
}
export type ExternalBlob = Uint8Array;
export interface Product {
  'id' : bigint,
  'inventory' : bigint,
  'name' : string,
  'description' : string,
  'productType' : ProductType,
  'qrCodeImage' : [] | [string],
  'image' : [] | [ExternalBlob],
  'price' : bigint,
}
export type ProductType = { 'book' : null } |
  { 'apparel' : null };
export interface Publication {
  'id' : bigint,
  'status' : PublicationStatus,
  'title' : string,
  'amazonLink' : [] | [string],
  'purchaseLink' : [] | [string],
  'availableQuantity' : bigint,
  'description' : string,
  'author' : string,
  'coverImage' : [] | [ExternalBlob],
  'summary' : string,
  'price' : bigint,
  'format' : PublicationFormat,
}
export type PublicationFormat = { 'hardcover' : null } |
  { 'paperback' : null } |
  { 'kindle' : null };
export type PublicationStatus = { 'outOfStock' : null } |
  { 'comingSoon' : null } |
  { 'forSale' : null };
export type SessionType = { 'mentoring' : null } |
  { 'consultation' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TrainingDocument {
  'id' : bigint,
  'title' : string,
  'documentUrl' : string,
  'shortDescription' : string,
}
export interface TrainingVideo {
  'id' : bigint,
  'title' : string,
  'shortDescription' : string,
  'videoUrl' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : [] | [string],
  'hasMembership' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : bigint,
  'title' : string,
  'thumbnail' : [] | [ExternalBlob],
  'description' : string,
  'category' : string,
  'videoUrl' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateMembership' : ActorMethod<[Principal], undefined>,
  'addProduct' : ActorMethod<[Product], bigint>,
  'addPublication' : ActorMethod<[Publication], undefined>,
  'addVideo' : ActorMethod<[Video], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<[string, string, SessionType, Time], bigint>,
  'checkBookingAccess' : ActorMethod<[], boolean>,
  'checkStoreAccess' : ActorMethod<[], boolean>,
  'checkVideoAccess' : ActorMethod<[], boolean>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[string, string, Array<bigint>, bigint], bigint>,
  'deactivateMembership' : ActorMethod<[Principal], undefined>,
  'deletePublication' : ActorMethod<[bigint], undefined>,
  'getAllApparel' : ActorMethod<[], Array<ApparelItem>>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getBiographyContent' : ActorMethod<
    [],
    {
      'headline' : string,
      'education' : string,
      'expertise' : string,
      'philosophy' : string,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<
    [],
    { 'email' : string, 'phone' : string, 'location' : string }
  >,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getCredentials' : ActorMethod<[], Credentials>,
  'getDisplayName' : ActorMethod<[], string>,
  'getDistinguishedServiceProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getMembershipPlans' : ActorMethod<[], Array<ShoppingItem>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getPublication' : ActorMethod<[bigint], Publication>,
  'getPublications' : ActorMethod<[], Array<Publication>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTrainingDocument' : ActorMethod<[bigint], TrainingDocument>,
  'getTrainingDocuments' : ActorMethod<[], Array<TrainingDocument>>,
  'getTrainingVideo' : ActorMethod<[bigint], TrainingVideo>,
  'getTrainingVideos' : ActorMethod<[], Array<TrainingVideo>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideos' : ActorMethod<[], Array<Video>>,
  'hasDisplayName' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isUserMember' : ActorMethod<[], boolean>,
  'purchaseMembership' : ActorMethod<[ShoppingItem, string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setDisplayName' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], bigint>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updatePublication' : ActorMethod<[bigint, Publication], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];